#! /bin/sh

##Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
compton &

#Single monitor
bspc monitor -d 1 2 3 4 5

##Main settings
bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false
bspc config focus_follows_pointer true

##Color theme (based on KDE Breeze colors)
bspc config focused_border_color "#3daee9"
bspc config normal_border_color "#2E3134"
bspc config presel_feedback_color "#4B4F51"
